# Generated by Django 2.2.10 on 2020-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_crawler', '0003_auto_20200309_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('is_contain_emoticon', models.BooleanField()),
                ('create_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcitementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('is_contain_emoticon', models.BooleanField()),
                ('create_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('is_contain_emoticon', models.BooleanField()),
                ('create_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PleasantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('is_contain_emoticon', models.BooleanField()),
                ('create_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurpriseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('is_contain_emoticon', models.BooleanField()),
                ('create_at', models.CharField(max_length=50)),
            ],
        ),
    ]
