# Generated by Django 2.2.10 on 2020-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_crawler', '0004_angrymodel_excitementmodel_fearmodel_pleasantmodel_surprisemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngrySampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcitementSampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FearSampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HappySampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PleasantSampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurpriseSampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
    ]
